### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Whitebrim** [IntelSDM/GUI-Framework#22]
What's the performance difference between [GUI-Framework](https://github.com/IntelSDM/GUI-Framework) and [dear imgui](https://github.com/ocornut/imgui) and [nuklear](https://github.com/Immediate-Mode-UI/Nuklear)?

**Comment by IntelSDM** [comment]
Dear IMGUI and Nuklear have faster renderers. Their actual UIs execute slower due to their bloat; as their UIs are meant for much more than cheat development. If you put this on IMGUI's dx11 renderer it would be faster. On the d2d1 backend, it is significantly slower though.

When it comes to the actual speed of UI execution due to the lack of bloat and simplicity this is much quicker.
